### ISSUE TITLE
Create Challenge Fails if User Does Not Enter in Correct Parameters

### ISSUE THREAD

**Issue by brianedmonds90** [christopherkalfas/sweatclause422#2]
Here's a small suggestion to make it a tad more user friendly.

The create Challenge endpoint fails if user does not enter in correct parameters to the web page form fields. 

Endpoint is here: http://radiant-wave-27873.herokuapp.com/challenges/new

To recreate bug, try to submit a new challenge without entering in any details. The application will display a server-side error message and still create a challenge item in the database. 

Recommended action is to force user to enter in required fields with some sort of javascript alert.

**Comment by christopherkalfas** [comment]
Thanks for the heads up, Brian! Got it fixed. Let me know if you see anything else.
